name: cd

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target SDLC environment'
        required: true
        default: 'sandbox'
        type: choice
        options:
          - sandbox
          - ci
          - qa
          - staging
          - preview
          - ctdev
          - cttest
          - prod

jobs:
  cd:
    uses: ebsi-cgoboncan/platform.github/.github/workflows/cd.yml
    with:
      env: ${{ inputs.env }}
