name: cd

on:
  workflow_run:
    workflows: [ci]
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-22.04    
    
    steps:
      - id: test
        run: echo ${{ toJSON(github.event.workflow_run) }}
