name: cd

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target SDLC environment'
        required: true
        default: 'sandbox'
        type: choice
        options:
          - sandbox
          - ci
          - qa
          - staging
          - preview
          - ctdev
          - cttest
          - prod
      deploy_version:
        description: "The version that we want to deploy"
        required: true
        type: string

  workflow_run:
    workflows: ["ci"]
    types:
      - completed
    branches:
      - develop
      - qa
      - staging
      - main

jobs:
  cd:
    uses: ebsi-cgoboncan/platform.github/.github/workflows/cd.yml
    with:
      env: ${{ inputs.env }}
