name: ci

on:
  pull_request:
    branches:
      - main
    
jobs:
  ci:
    runs-on: ubuntu-22.04
    outputs:
      package_version: ${{ steps.test.outputs.package_version }}
    steps:
      - id: test
        uses: ebsi-cgoboncan/platform.github/.github/workflows/ci.yml@main
